import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillGithub,
  AiFillInstagram,
  AiFillLinkedin,
  AiFillGoogleCircle,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import jsPDF from "jspdf";
import design from "../public/design.png";
import customization from "../public/3d.png";
import customizationv2 from "../public/3d2.png";
import cryptoo from "../public/cryptoo.png";
import { useState } from "react";
import { draftMode } from "next/dist/client/components/headers";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [saving, setSaving] = useState(false);

  function saveResume() {
    setSaving(true);
    var doc = new jsPDF("portrait", "px", "a4", false);
    doc.addImage(
      "https://i.ibb.co/tYBDQS6/Gtari-Mohamed-Aziz-1.jpg",
      "JPG",
      0,
      0,
      417,
      653
    );
    doc.save("resume.pdf");
    setSaving(false);
  }

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Med Aziz Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/dev-ed-wave.png" />
      </Head>
      <main className="bg-white px-10 md:text-center md:px-20 lg:px-40 dark:bg-gray-800">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">developedbyed</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className={`bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 ${
                    darkMode ? "white-text" : ""
                  }`}
                  onClick={saveResume}
                  disabled={saving}
                  style={{ cursor: saving ? "not-allowed" : "pointer" }}
                >
                  <button>Resume</button>
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Med Aziz Gtari
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl ">
              Full Stack Js Developer{" "}
            </h3>
            <p className="text-md py-5 leading-8 md:text-xl max-w-lg mx-auto">
              Hi,I am a passionate web developer with a certificate of
              completion from{" "}
              <span className="text-teal-500">
                {" "}
                the Full-Stack JavaScript bootcamp
              </span>{" "}
              . I have gained solid experience in developing projects using
              technologies such as{" "}
              <span className="text-teal-500">
                {" "}
                React.js , Next.js, Three.js,
              </span>{" "}
              and Figma for design. I have an excellent understanding of both
              front-end and back-end development, and I have a strong passion
              for creating exceptional user experiences. I am constantly seeking
              new opportunities to enhance my technical skills and take on new
              challenges.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://www.linkedin.com/">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/l3aziz">
              <AiFillGithub />
            </a>
            <a href="https://www.instagram.com/med_aziz_gtari/">
              <AiFillInstagram />
            </a>
          </div>
          <div className=" relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" alt="" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">A Glimpse of My Work</h3>
            <p className="text-md py-2 leading-8 text-gray-80">
              Throughout my freelance development journey, I have gained
              extensive experience in remote work, collaborating with various{" "}
              <span className="text-teal-500">agencies</span> and providing
              valuable consultation.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <div className="flex justify-center">
                <Image src={design} width={400} height={400} alt="" />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">News Web Site</h3>
              <p className="py-2">
                The app offers an intuitive and visually appealing interface
                that ensures a smooth user experience. Users can navigate
                through different news categories, search for specific topics,
                and customize their news preferences.
              </p>
              <h4 className="py-4 text-teal-600">React Js I Use</h4>
              <p className="text-gray-800 py-1"> NewsToday </p>
              <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
                <a href="https://github.com/l3aziz/project-news-today.git">
                  <AiFillGithub />
                </a>
              </div>
            </div>
          </div>
          <div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
              <div className="flex justify-center">
                <Image src={cryptoo} width={400} height={400} alt="" />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Cryptoverse Web Site
              </h3>
              <p className="py-2">
                Cryptoverse: Your Gateway to the World of Digital Currency and
                Blockchain.
              </p>
              <h4 className="py-4 text-teal-600">React Js I Use</h4>
              <h4 className="py-4 text-teal-600">redux toolkit Use</h4>
              <p className="text-gray-800 py-1"> Cryptoverse </p>
              <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
                <a href="https://github.com/l3aziz/project-news-today.git">
                  <AiFillGithub />
                </a>
                <a href="https://cryotoapp-fn2l.vercel.app/">
                  <AiFillGoogleCircle />
                </a>
              </div>
            </div>
            <div className="flex justify-center">
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                <div className="flex justify-center">
                  <Image src={customization} width={400} height={400} alt="" />
                </div>
                <h3 className="text-lg font-medium pt-8 pb-2">
                  Customization Web Site
                </h3>
                <p className="py-2">
                  Create your unique and exclusive shirt with our brand-new 3D
                  customization tool. Unleash your imagination and define your
                  own style.
                </p>
                <h4 className="py-4 text-teal-600">
                  vite React + Next Js + Three Js
                </h4>
                <p className="text-gray-800 py-1"> 3D-Customization </p>
                <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
                  <a href="https://github.com/l3aziz/3D_customization.git">
                    <AiFillGithub />
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section></section>
      </main>
    </div>
  );
}
